### PR TITLE
Some cleanups

### PR DESCRIPTION
**Pull request by pvizeli**
- Remove windows installer
- Cleanups

### CODE REVIEW

**Comment by dude0001** [comment]
I'm basically trying to get hass.io running in Docker on Windows. Why did the Windows install get pulled out? I patched this back in on a local repo and tweaked the script to pull hassio_supervisor.ps1 from my local machine. It seemed to work, and the supervisor Windows service is running. Is there documentation on what I need to do next?

**Comment by pvizeli** [comment]
@dude0001 I think you are more lucky to use HassOS inside hyperV or a VM. Anyway what I need is a documentation and some one they are real maintain this.

What will work better with that way as to run HassOS on Windows?

**Comment by tnagels** [comment]
Strange that the "acceptable" solution is to remove the .ps1 file. 

Hassio (the official VM) will not run under Hyper V and now you also removed the Windows Docker option. So basically you are forcing people with a Windows server to either (1) use a different hypervisor with all related limitations, (2) go through the painful process of installing a full Linux Vm and trying to make hass.io work on that or (3) buy additional hardware but not RPI as this is underpowered for most hassio installations...

I don't see the benefit of any of these solutions.

**Comment by dude0001** [comment]
I ended up just installing full HA in a python virtual environment on Windows Server. I had trouble getting zwave to work and had to submit a PR for the python-openzwave module [https://github.com/OpenZWave/python-openzwave/pull/133](https://github.com/OpenZWave/python-openzwave/pull/133) After installing that everything works great on Windows Server native.

**Comment by tnagels** [comment]
Yes, that is an alternative, but I wanted the full Hassio experience, not Home Assistant.

After some searching I ended up installing an Ubuntu Server VM and using [this script](https://github.com/tnagels/hass.io-01) to install Hassio with a single command.

My system runs on an 8th generation Intel Nuw with ah i7 so it has plenty of power to do it this way.

**Pull request merged**
