### PR TITLE
Add freetds-dev and pymssql

### PR DESCRIPTION
**Pull request by datafx**
Adds support for Microsoft SQL Server.  
We have to install the dev branch of pymssql due to a conflict with freetds 1.0 in the current release version.
https://github.com/pymssql/pymssql/issues/432

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @datafx, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;hassio-build#24).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by pvizeli** [comment]
I will reorder the build for 0.51. So that the size of image should go smaller. So we need do:
```
RUN install lib and dev
 && build stuff
 && remove dev
```

**Comment by datafx** [comment]
Something like this instead?
# Pymssql
RUN apk --no-cache add unixodbc freetds freetds-dev \
    && pip3 install --no-cache-dir git+https://github.com/pymssql/pymssql.git \
    && apk --no-cache del freetds-dev

**Comment by datafx** [comment]
I'm not sure which way you are trying to go with this, but maybe we want to stick all the database components together? 
```
RUN apk --no-cache add \
    mariadb-dev \
    postgresql-dev \
    unixodbc \
    freetds \
    freetds-dev \
    && pip3 install --no-cache-dir mysqlclient psycopg2 \
    && pip3 install --no-cache-dir git+https://github.com/pymssql/pymssql.git \
    && apk --no-cache del mariadb-dev postgresql-dev freetds-dev

**Comment by pvizeli** [comment]
perfect. thanks. Is integreate in: https://github.com/home-assistant/hassio-build/pull/25

**Pull request closed without merging**
