### PR TITLE
Add support for Orange Pi PC2

### PR DESCRIPTION
**Pull request by alex-asp**

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @alex-asp, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;hassio-build#139).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by alex-asp** [comment]
People compare device processors to install the correct version, here is an example [https://www.youtube.com/watch?v=kornNzDSneI](url)

**Comment by alex-asp** [comment]
Please add support for orangepi-pс2 as it is similar to the device raspberrypi3-64

**Comment by rbray89** [comment]
@alex-asp To add support, support must first be added to https://github.com/home-assistant/hassos.

**Pull request closed without merging**
