### PR TITLE
Add dht support.

### PR DESCRIPTION
**Pull request by gollo**
Fixes [#178](https://github.com/home-assistant/hassio/issues/178)

Couldn't find a better way to get the archive/version from GIT.

### CODE REVIEW

**Comment by pvizeli** [comment]
We need fake the platform https://github.com/adafruit/Adafruit_Python_DHT/blob/master/setup.py#L20-L36

We can patch the setup or need call the like `python3 setup.py install --xy` or you have a better idea...

**Comment by gollo** [comment]
That works to compile it. But unfortunately it detects the hardware at runtime which it can't do in a container.  This is a massive can of worms, I don't have the time to pursue further (and I don't have a DHT sensor!) so I'm closing this PR.  It seems like there are going to be things that just can't be run in a container (except maybe with massive upstream changes). That needs to be thought about from a HASSIO POV.

**Comment by pvizeli** [comment]
It should work since it run on host kernel inside docker. It have also work before but we remove all build tools from image and that is the reason why it doesn't "work" anymore.

**Comment by pvizeli** [comment]
Good work 👍

**Pull request merged**
