### PR TITLE
HASS.io on Windows

### PR DESCRIPTION
**Pull request by sytone**
This is a first pass at using docker on windows. 

Current Known Issues:
The HC process uses unix sockets, not available on windows. 
Option: Move to REST based HC service for windows and update the python code to be aware of the OS the host is running. 

Addon Validation:
Played with ones, have a issue where samba will not start as you are on windows and the samba port is already in use as docker tries to bind to the local IP of the machine on the same port. 
Option: Use alternative access method to configuration or finally complete my git based component to allow backup/restore and remote editing. :)

### CODE REVIEW

**Comment by pvizeli** [comment]
Amazing. I will review it tonight :+1:

For HC: we can move it also to a socket connection. So if the unixsocket is not exists we use a socket to `172.17.0.1`. Can that work with Windows?

**Comment by sytone** [comment]
If it is a plain socket connection then it will work. PowerShell has full access to the .Net framework so you can make socket connections. 

Doing a quick search here is a example of a TCP socket connection. http://www.leeholmes.com/blog/2009/10/28/scripting-network-tcp-connections-in-powershell/

**Comment by pvizeli** [comment]
Greate work 👍  I think we can merge that.

Strange is that the docker unix socket works?

**Comment by pvizeli** [comment]
I hope you will help me to improve the Windows support :+1: 

You can add this to Website as experimentel and make a note to README? You can also use Version.json with `windows` to version control for HostControl

**Comment by sytone** [comment]
Hey, back from a break. I will get this looked at this week.

**Pull request merged**
